force-app/main/default/objects/CommerceFlag__c/CommerceFlag__c.object-meta.xml
<CustomObject>
    <label>Flag</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Flags</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CommerceFlag__c/fields/Animate__c.field-meta.xml
<CustomField>
    <fullName>Animate__c</fullName>
    <label>Animate</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pulse</fullName>
            </value>
            <value>
                <fullName>Stretch</fullName>
            </value>
            <value>
                <fullName>Swing</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/CommerceFlag__c/fields/Background_Color__c.field-meta.xml
<CustomField>
    <fullName>Background_Color__c</fullName>
    <label>Background Color</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommerceFlag__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Color</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommerceFlag__c/fields/Rotate__c.field-meta.xml
<CustomField>
    <fullName>Rotate__c</fullName>
    <label>Rotate</label>
    <length>25</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CommerceFlag__c/fields/Translation__c.field-meta.xml
<CustomField>
    <fullName>Translation__c</fullName>
    <label>Translation</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Product2/fields/Flag__c.field-meta.xml
<CustomField>
    <fullName>Flag__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Flag</label>
    <referenceTo>CommerceFlag__c</referenceTo>
    <relationshipLabel>Products</relationshipLabel>
    <relationshipName>Products</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/B2bCategoryAddProductFlagsController.cls
public with sharing class B2bCategoryAddProductFlagsController {
    @AuraEnabled(cacheable=true)
    public static List<Product2> getProductsFlags(String productIds){
        Set<Id> prdIds = new Set<Id>();
        for(String id : productIds.split(',')){
            prdIds.add(id);
        }
        return [SELECT Flag__c, Flag__r.Label__c, Flag__r.Color__c, Flag__r.Background_Color__c, Flag__r.Rotate__c, Flag__r.Animate__c, Flag__r.Translation__c
                FROM Product2
                WHERE Id = :prdIds AND Flag__c != null];
    }

}